- name: Mete o answer file lah
  include: tasks/push_facts.yml


- name: Chama o foreman-installer
  command: foreman-installer --scenario foreman
           --foreman-admin-username "{{ ansible_local.foreman_facts.rhn.admin }}"
           --foreman-admin-password "{{ ansible_local.foreman_facts.rhn.passwd }}"
#           --foreman-initial-organization "{{ ansible_local.foreman_facts.rhn.foreman_orgname }}"
#           --foreman-initial-location "{{ ansible_local.foreman_facts.rhn.foreman_location }}"
