#- shell: "/bin/echo fproxy_to_foreman_ports {{ item }}"
#  with_items: "{{ fproxy_to_foreman_ports + fproxy_to_client_ports }}"

- firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    #port: "{{ fproxy_to_foreman_ports + fproxy_to_client_ports }}"
    port: "{{ item }}"
  with_items: "{{ fproxy_to_foreman_ports + fproxy_to_client_ports }}"

- firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    service: "{{ item }}"
  with_items: "{{ fproxy_to_foreman_svcs + fproxy_to_client_svcs }}"
