- name: Update the system before next step
  yum:
    name: '*'
    state: latest
  tags:
    - task_update_system

- name: Install core packages
  yum:
    #name: "{{ item }}"
    name: "{{ core_packages }}"
    state: latest
#  with_items: "{{ core_packages }}"
