- name: Carrega as vars
  include_vars: vars/EDIT_hostname.vars

- name: Define o hostname
  hostname:
    name: "{{ foreman_hostname }}"

- name: Instala pacotes necessarios do modulo nmcli
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - NetworkManager-glib
    - nm-connection-editor
    - libsemanage-python
    - policycoreutils-python


- name: Define o endereco IP
  nmcli:
    conn_name: eth0
    autoconnect: yes
    dns4: 192.168.123.200
    gw4: 192.168.123.5
    ip4: "{{ foreman_ipaddr }}"
    state: present
    type: ethernet

- name: Adiciona essas informacoes ao servidor DNS interno
  hosts: hess-dns-server
  lineinfile:
    dest: /etc/host.d/04_foreman
    state: present
    regexp: '^{{ foreman_ipaddr }}'
    line: "{{ foreman_ipaddr }} {{ foreman_hostname }}"
    create: yes

- name: Remonta o /etc/hosts do servidor DNS
  hosts: hess-dns-server
  shell: /bin/bash /etc/cron.weekly/upd_hostsfile merge

- name: Reinicia o servico dnsmasq
  hosts: hess-dns-server
  service:
    name: dnsmasq
    state: restarted
