---
- hosts: foreman_server
  tasks:

    - name: Collect host OS details to guide next steps
      include: tasks/collect_os_info.yml
      tags:
        - server
        - phase_prep
        - phase_collect

    - name: Set up the foreman firewall
      include: tasks/server_firewall.yml
      tags:
        - server
        - phase_prep
        - firewall

    - name: Enable necessary repos
      include: tasks/enable_required_repos.yml
      tags:
        - foreman
        - phase_prep
        - phase_packages

    - name: Install mandatory packages and start mandatory services
      include: tasks/install-mandatory-packages.yml
      tags:
        - foreman
        - phase_prep
        - phase_packages

    - name: Install core packages
      include: tasks/install-core-packages.yml
      tags:
        - foreman
        - phase_prep
        - phase_packages


#vim: ai ts=2 sw=2 et
