---
## To be able to run this task, make sure to add your SSH pubkey as root user.
## Note that is expected a pre-existing ssh key pairs to be automatically copied to the server.
# ssh-copy-id -i ~/.ssh/id_rsa.pub root@<SERVER>
# ansible-playbook -u root --tags="prereq_as_root" main.yaml

  - name: Create devops user to deploy Foreman
    user: 
      name: devops
      shell: /bin/bash
      groups: wheel
      home: /home/devops
    tags:
      - prereq_as_root
    register: create_user_result

  - name: Add ssh key to user's devops
    authorized_key:
      user: devops
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    when: create_user_result.rc == 0
    tags:
      - prereq_as_root
    register: add_pubkey_result

  - name: Allow members of wheel to run sudo without password
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel\s'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    when: add_pubkey_result == 0
    tags:
      - prereq_as_root
    register: sudoers_result

# vim:sw=2:ts=2:et:
