---
## To be able to run this task, make sure to add your SSH pubkey as root user.
## Note that is expected a pre-existing ssh key pairs to be automatically copied to the server.
# ssh-copy-id -i ~/.ssh/id_rsa.pub root@<SERVER>
# ansible-playbook -u root --tags="prereq_as_root" main.yml
#
  - name: Create devops user to deploy Foreman
    user: 
      name: devops
      shell: /bin/bash
      groups: "{{ superadmin_group }}"
      home: /home/devops
    tags:
      - prereq_as_root

  - name: Add ssh key to user's devops
    authorized_key:
      user: devops
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    tags:
      - prereq_as_root

  - name: Allow members of wheel to run sudo without password
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%{{ superadmin_group }}\s'
      line: '%{{ superadmin_group }} ALL=(ALL) NOPASSWD: ALL'
    tags:
      - prereq_as_root

# vim:sw=2:ts=2:et:
